// priority: 0

settings.logAddedRecipes = false
settings.logRemovedRecipes = false
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

onEvent('recipes', event => {
	// Change recipes here
	// event.remove({output: 'minecraft:stone_pickaxe'})
	// event.remove({input: '#forge:dusts/redstone'})
	// event.remove({mod: 'quartzchests'})
	// event.remove({id: 'minecraft:glowstone'})
	
	// Delete Creative and Debug Items
	event.remove({output: '#excompressum:baits'})
	event.remove({output: '#excompressum:heavy_sieve'})
	event.remove({output: '#excompressum:sieves'})
	event.remove({output: 'ae2:debug_card'})
	event.remove({output: 'ae2:debug_eraser'})
	event.remove({output: 'ae2:debug_meteorite_placer'})
	event.remove({output: 'ae2:debug_replicator_card'})
	event.remove({output: 'alexsmobs:falconry_glove_hand'})
	event.remove({output: 'alexsmobs:falconry_glove_inventory'})
	event.remove({output: 'alexsmobs:red_sand_circle'})
	event.remove({output: 'alexsmobs:sand_circle'})
	event.remove({output: 'alexsmobs:skelewag_sword_hand'})
	event.remove({output: 'alexsmobs:skelewag_sword_inventory'})
	event.remove({output: 'alexsmobs:tab_icon'})
	event.remove({output: 'alexsmobs:vine_lasso_hand'})
	event.remove({output: 'alexsmobs:vine_lasso_inventory'})
	event.remove({output: 'autooredictconv:converter'})
	event.remove({output: 'citadel:debug'})
	event.remove({output: 'citadel:effect_item'})
	event.remove({output: 'citadel:fancy_item'})
	event.remove({output: 'computercraft:computer_command'})
	event.remove({output: 'create_things_and_misc:hot_air_ballon_spawn_egg'})
	event.remove({output: 'excompressum:auto_heavy_sieve'})
	event.remove({output: 'excompressum:auto_sieve'})
	event.remove({output: 'excompressum:bat_zapper'})
	event.remove({output: 'excompressum:chicken_stick'})
	event.remove({output: 'excompressum:evolved_orechid'})
	event.remove({output: 'excompressum:iron_mesh'})
	event.remove({output: 'excompressum:mana_hammer'})
	event.remove({output: 'excompressum:mana_sieve'})
	event.remove({output: 'excompressum:ore_smasher'})
	event.remove({output: 'exnihilosequentia:bee_doll'})
	event.remove({output: 'exnihilosequentia:blaze_doll'})
	event.remove({output: 'exnihilosequentia:crafting_doll'})
	event.remove({output: 'exnihilosequentia:diamond_mesh'})
	event.remove({output: 'exnihilosequentia:emerald_mesh'})
	event.remove({output: 'exnihilosequentia:end_cake'})
	event.remove({output: 'exnihilosequentia:enderman_doll'})
	event.remove({output: 'exnihilosequentia:flint_mesh'})
	event.remove({output: 'exnihilosequentia:guardian_doll'})
	event.remove({output: 'exnihilosequentia:iron_mesh'})
	event.remove({output: 'exnihilosequentia:shulker_doll'})
	event.remove({output: 'exnihilosequentia:string_mesh'})
	event.remove({output: 'extendedcrafting:recipe_maker'})
	event.remove({output: 'ftbquests:barrier'})
	event.remove({output: 'ftbquests:custom_icon'})
	event.remove({output: 'ftbquests:detector'})
	event.remove({output: 'ftbquests:loot_crate_opener'})
	event.remove({output: 'ftbquests:missing_item'})
	event.remove({output: 'ftbquests:stage_barrier'})
	event.remove({output: 'mcjtylib:multipart'})
	event.remove({output: 'mekanism:bounding_block'})
	event.remove({output: 'minecraft:barrier'})
	event.remove({output: 'minecraft:bedrock'})
	event.remove({output: 'minecraft:bundle'})
	event.remove({output: 'minecraft:chain_command_block'})
	event.remove({output: 'minecraft:command_block_minecart'})
	event.remove({output: 'minecraft:command_block'})
	event.remove({output: 'minecraft:filled_map'})
	event.remove({output: 'minecraft:jigsaw'})
	event.remove({output: 'minecraft:knowledge_book'})
	event.remove({output: 'minecraft:light'})
	event.remove({output: 'minecraft:repeating_command_block'})
	event.remove({output: 'minecraft:structure_block'})
	event.remove({output: 'minecraft:structure_void'})
	event.remove({output: 'storagedrawers:creative_vending_upgrade'})
	event.remove({output: 'supplementaries:checker_vertical_slab'})
	event.remove({output: 'supplementaries:pancake_disc'})
	event.remove({output: 'supplementaries:placeable_item'})
	event.remove({output: 'unusualend:dragon_lamp_on'})
	event.remove({output: 'unusualend:fading_block_on'})
	event.remove({output: 'unusualend:infused_ender_respawn_altar'})
	event.remove({output: 'wormhole:portal'})
	
	event.remove({input: '#excompressum:baits'})
	event.remove({input: '#excompressum:heavy_sieve'})
	event.remove({input: '#excompressum:sieves'})
	event.remove({input: 'ae2:debug_card'})
	event.remove({input: 'ae2:debug_eraser'})
	event.remove({input: 'ae2:debug_meteorite_placer'})
	event.remove({input: 'ae2:debug_replicator_card'})
	event.remove({input: 'alexsmobs:falconry_glove_hand'})
	event.remove({input: 'alexsmobs:falconry_glove_inventory'})
	event.remove({input: 'alexsmobs:red_sand_circle'})
	event.remove({input: 'alexsmobs:sand_circle'})
	event.remove({input: 'alexsmobs:skelewag_sword_hand'})
	event.remove({input: 'alexsmobs:skelewag_sword_inventory'})
	event.remove({input: 'alexsmobs:tab_icon'})
	event.remove({input: 'alexsmobs:vine_lasso_hand'})
	event.remove({input: 'alexsmobs:vine_lasso_inventory'})
	event.remove({input: 'autooredictconv:converter'})
	event.remove({input: 'citadel:debug'})
	event.remove({input: 'citadel:effect_item'})
	event.remove({input: 'citadel:fancy_item'})
	event.remove({input: 'computercraft:computer_command'})
	event.remove({input: 'create_things_and_misc:hot_air_ballon_spawn_egg'})
	event.remove({input: 'excompressum:auto_heavy_sieve'})
	event.remove({input: 'excompressum:auto_sieve'})
	event.remove({input: 'excompressum:bat_zapper'})
	event.remove({input: 'excompressum:chicken_stick'})
	event.remove({input: 'excompressum:evolved_orechid'})
	event.remove({input: 'excompressum:iron_mesh'})
	event.remove({input: 'excompressum:mana_hammer'})
	event.remove({input: 'excompressum:mana_sieve'})
	event.remove({input: 'excompressum:ore_smasher'})
	event.remove({input: 'exnihilosequentia:bee_doll'})
	event.remove({input: 'exnihilosequentia:blaze_doll'})
	event.remove({input: 'exnihilosequentia:crafting_doll'})
	event.remove({input: 'exnihilosequentia:diamond_mesh'})
	event.remove({input: 'exnihilosequentia:emerald_mesh'})
	event.remove({input: 'exnihilosequentia:end_cake'})
	event.remove({input: 'exnihilosequentia:enderman_doll'})
	event.remove({input: 'exnihilosequentia:flint_mesh'})
	event.remove({input: 'exnihilosequentia:guardian_doll'})
	event.remove({input: 'exnihilosequentia:iron_mesh'})
	event.remove({input: 'exnihilosequentia:shulker_doll'})
	event.remove({input: 'exnihilosequentia:string_mesh'})
	event.remove({input: 'extendedcrafting:recipe_maker'})
	event.remove({input: 'ftbquests:barrier'})
	event.remove({input: 'ftbquests:custom_icon'})
	event.remove({input: 'ftbquests:detector'})
	event.remove({input: 'ftbquests:loot_crate_opener'})
	event.remove({input: 'ftbquests:missing_item'})
	event.remove({input: 'ftbquests:stage_barrier'})
	event.remove({input: 'mcjtylib:multipart'})
	event.remove({input: 'mekanism:bounding_block'})
	event.remove({input: 'minecraft:barrier'})
	event.remove({input: 'minecraft:bedrock'})
	event.remove({input: 'minecraft:bundle'})
	event.remove({input: 'minecraft:chain_command_block'})
	event.remove({input: 'minecraft:command_block_minecart'})
	event.remove({input: 'minecraft:command_block'})
	event.remove({input: 'minecraft:filled_map'})
	event.remove({input: 'minecraft:jigsaw'})
	event.remove({input: 'minecraft:knowledge_book'})
	event.remove({input: 'minecraft:light'})
	event.remove({input: 'minecraft:repeating_command_block'})
	event.remove({input: 'minecraft:structure_block'})
	event.remove({input: 'minecraft:structure_void'})
	event.remove({input: 'storagedrawers:creative_vending_upgrade'})
	event.remove({input: 'supplementaries:checker_vertical_slab'})
	event.remove({input: 'supplementaries:pancake_disc'})
	event.remove({input: 'supplementaries:placeable_item'})
	event.remove({input: 'unusualend:dragon_lamp_on'})
	event.remove({input: 'unusualend:fading_block_on'})
	event.remove({input: 'unusualend:infused_ender_respawn_altar'})
	event.remove({input: 'wormhole:portal'})

	// Oganesson
	event.remove({input: 'chemlib:oganesson'})
	event.remove({output: 'chemlib:oganesson'})
	event.remove({id: 'alchemistry:dissolver/dragon_breath'})
	
})

