// priority: 0

onEvent('jei.hide.items', event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')

	// Hide Creative and Debug Items
	event.hide('#excompressum:baits')
	event.hide('#excompressum:heavy_sieve')
	event.hide('#excompressum:sieves')
	event.hide('ae2:debug_card')
	event.hide('ae2:debug_eraser')
	event.hide('ae2:debug_meteorite_placer')
	event.hide('ae2:debug_replicator_card')
	event.hide('alexsmobs:falconry_glove_hand')
	event.hide('alexsmobs:falconry_glove_inventory')
	event.hide('alexsmobs:red_sand_circle')
	event.hide('alexsmobs:sand_circle')
	event.hide('alexsmobs:skelewag_sword_hand')
	event.hide('alexsmobs:skelewag_sword_inventory')
	event.hide('alexsmobs:tab_icon')
	event.hide('alexsmobs:vine_lasso_hand')
	event.hide('alexsmobs:vine_lasso_inventory')
	event.hide('autooredictconv:converter')
	event.hide('citadel:debug')
	event.hide('citadel:effect_item')
	event.hide('citadel:fancy_item')
	event.hide('craftcreator:create_recipe_creator')
	event.hide('craftcreator:minecraft_recipe_creator')
	event.hide('craftcreator:thermal_recipe_creator')
	event.hide('create_things_and_misc:hot_air_ballon_spawn_egg')
	event.hide('custommachinery:box_creator_item')
	event.hide('custommachinery:machine_creator_item')
	event.hide('excompressum:auto_heavy_sieve')
	event.hide('excompressum:auto_sieve')
	event.hide('excompressum:bat_zapper')
	event.hide('excompressum:chicken_stick')
	event.hide('excompressum:evolved_orechid')
	event.hide('excompressum:iron_mesh')
	event.hide('excompressum:mana_hammer')
	event.hide('excompressum:mana_sieve')
	event.hide('excompressum:ore_smasher')
	event.hide('exnihilosequentia:bee_doll')
	event.hide('exnihilosequentia:blaze_doll')
	event.hide('exnihilosequentia:crafting_doll')
	event.hide('exnihilosequentia:diamond_mesh')
	event.hide('exnihilosequentia:emerald_mesh')
	event.hide('exnihilosequentia:end_cake')
	event.hide('exnihilosequentia:enderman_doll')
	event.hide('exnihilosequentia:flint_mesh')
	event.hide('exnihilosequentia:guardian_doll')
	event.hide('exnihilosequentia:iron_mesh')
	event.hide('exnihilosequentia:shulker_doll')
	event.hide('exnihilosequentia:string_mesh')
	event.hide('extendedcrafting:recipe_maker')
	event.hide('ftbquests:barrier')
	event.hide('ftbquests:custom_icon')
	event.hide('ftbquests:detector')
	event.hide('ftbquests:loot_crate_opener')
	event.hide('ftbquests:missing_item')
	event.hide('ftbquests:stage_barrier')
	event.hide('mcjtylib:multipart')
	event.hide('mekanism:bounding_block')
	event.hide('minecraft:barrier')
	event.hide('minecraft:bedrock')
	event.hide('minecraft:bundle')
	event.hide('minecraft:chain_command_block')
	event.hide('minecraft:command_block_minecart')
	event.hide('minecraft:command_block')
	event.hide('minecraft:filled_map')
	event.hide('minecraft:jigsaw')
	event.hide('minecraft:knowledge_book')
	event.hide('minecraft:light')
	event.hide('minecraft:repeating_command_block')
	event.hide('minecraft:structure_block')
	event.hide('minecraft:structure_void')
	event.hide('storagedrawers:creative_vending_upgrade')
	event.hide('supplementaries:checker_vertical_slab')
	event.hide('supplementaries:pancake_disc')
	event.hide('supplementaries:placeable_item')
	event.hide('unusualend:dragon_lamp_on')
	event.hide('unusualend:fading_block_on')
	event.hide('unusualend:infused_ender_respawn_altar')
	event.hide('wormhole:portal')
	event.hide(Item.of('custommachinery:structure_creator', '{custommachinery:{}}'))

})